library("iSEE")
library("scRNAseq")
example(iSEE, ask=FALSE)
library("scater")
sce <- logNormCounts(sce, exprs_values="tophat_counts")
set.seed(1000)
sce <- runPCA(sce)
sce <- runTSNE(sce)
reducedDimNames(sce)
rowData(sce)$mean_log <- rowMeans(logcounts(sce))
rowData(sce)$var_log <- apply(logcounts(sce), 1, var)
app <- iSEE(sce)
options(shiny.port = 7776)
shiny::runApp(app)
